name: Ruby

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.5.7
    - name: Build project
      run: docker-compose up --build -d
    - name: Run API tests
      run: docker-compose run -e "RAILS_ENV=test" api rake test
    - name: Run Client tests
      run: docker-compose run client yarn run test:unit