name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build project
      run: docker-compose up --build -d
    - name: Run API tests
      run: docker-compose run -e "RAILS_ENV=test" api rake test
    - name: Run Client tests
      run: docker-compose run client yarn run test:unit
